### ISSUE TITLE
Deprecation warning on hasMethod

### ISSUE THREAD

**Issue by danopia** [jagi/meteor-astronomy-slug-behavior#13]
I updated to the latest version of all my Astronomy packages, and got a metric fucktonne of deprecation warnings when running my database update script. Seems to be related to the hasMethod call when slugging.

**Comment by lukejagodzinski** [comment]
Hmm yes I didn't update this behavior to reflect changes that I've made in last versions. I will update this package.

**Comment by lukejagodzinski** [comment]
Fixed in 3.0.0. Right now there is also no default value for the `fieldName` option in the slug behavior so you have to set it manually.

**Comment by danopia** [comment]
Thank you! 👍
