### ISSUE TITLE
invalid token if label contains -

### ISSUE THREAD

**Issue by moeen-basra** [jagi/meteor-astronomy-slug-behavior#14]
Hi @jagi I'm newbie I was trying the slug behaviour, if there is a "-" in label then I think slug must ommit the spaces and let the "-" as it e.g.

Label: **This is - label of post**
Slug: **this-is-label-of-post**

in current scenario it is creating a slug as: **this-is---label-of-post**

**Comment by lukejagodzinski** [comment]
Hi, yes I know that it works that way with `-` but I don't think it's a big deal. However, I will probably not gonna change that as I don't want to introduce compatibility breaking changes. It would break uniqueness of slugs when adding new records to already existing ones.

**Comment by lukejagodzinski** [comment]
However, if you want to achieve that you can create your own helper that will enhance slug creation:

```js
const Item = Class.create({
  name: 'Item',
  collection: Items,
  fields: {
    title: String
  },
  helpers: {
    getTitle() {
      return this.title.replace(/[-_]+/gm, '').replace(/\s+/gm, ' ');
    }
  },
  behaviors: {
    slug: {
      helperName: 'getTitle'
    }
  }
});
```

I hope that will help

**Comment by moeen-basra** [comment]
thank @jagi that really helps.
