### ISSUE TITLE
unique option unclear

### ISSUE THREAD

**Issue by janat08** [jagi/meteor-astronomy-slug-behavior#15]
I'm unclear if unique field is meant to convey that stubs are expected to be unique, or if the library doesn't have to ensure uniqueness as the user will do so himself.

It's documented like so:     // A flag indicating if a slug is unique.

**Comment by lukejagodzinski** [comment]
Library will make sure that slug is unique. Take a look at the code here https://github.com/jagi/meteor-astronomy-slug-behavior/blob/v2/lib/behavior/generateSlug.js#L56

If it finds document with the same slug, then it will start adding numbers to the end of the slug to make it unique.
