### ISSUE TITLE
[1.0.0 RC 1] slug: null

### ISSUE THREAD

**Issue by laurentpayot** [jagi/meteor-astronomy-slug-behavior#3]
I am using

<pre>
jagi:astronomy                     1.0.0-rc.4  
jagi:astronomy-slug-behavior       1.0.0-rc.1  
jagi:astronomy-timestamp-behavior  1.0.0-rc.1  
jagi:astronomy-validators          1.0.0-rc.2  
</pre>

and the timestamps are working well. But slugs stopped working after 1.0.0 RC 1.
I use:

``` javascript
    slug: {
      fieldName: 'title',
      slugFieldName: 'slug',
      canUpdate: true,
      unique: true,
      separator: '-'
    }
```

Now in all my database records I have <code>"slug" : null,</code> instead of slug fields.

**Comment by lukejagodzinski** [comment]
Can you create reproduction repository? I have tests for the slug behavior and everything works correctly so I'm assuming that you have error somewhere.

**Comment by laurentpayot** [comment]
I'm away from any decent computer for a couple of days but I will create one asap.

**Comment by lukejagodzinski** [comment]
Are you sure that you are using the `set` method to set a value of the `title` field?

**Comment by laurentpayot** [comment]
I will check again that I'm always using <code>set</code>, but this problem also occurs after I instantiate an object with a "title" parameter and save it. And with inherited classes or not. I will try to find the time to create a reproduction repository this week.

**Comment by lukejagodzinski** [comment]
It would be great if you could create a reproduction until the end of this week because in the next week I'm planning a release of the 1.0.0 version

**Comment by laurentpayot** [comment]
I found out that the bug only occurs when you instantiate an object like this:

``` javascript
var obj = new Item({title: "déjà vu"});
obj.save():
```

It's working when you do the following:

``` javascript
var obj = new Item();
obj.set('title', "déjà vu");
obj.save();
```

The problem is that I almost always use the first way, that was working prior 1.0.0 RC 1.

I will create a reproduction repository this evening if you can't reproduce this bug.

**Comment by lukejagodzinski** [comment]
Oh I see. Sorry for that, but this had have to be changed. You have to use the second approach.
The first approach is used when you want to insert a document with the `_id` field already filled. For example if you have some data from other database and you want to insert it into the current database.
It's also not so hard to change it in all places where you used it:

``` js
var doc = new Item({title: 'Title', number: 123});
```

``` js
var doc = new Item();
doc.set({title: 'Title', number: 123});
```

You DO NOT have to add each property separately.

``` js
var doc = new Item();
doc.set('title', 'Title');
doc.set('number', 123);
```

**Comment by laurentpayot** [comment]
Oh great I didnt notice the <code>doc.set({title: 'Title', number: 123});</code> syntax. It's all right then. Thanks!
