### ISSUE TITLE
slug is not being generated when instance is created

### ISSUE THREAD

**Issue by zvictor** [jagi/meteor-astronomy-slug-behavior#5]
# Problem

I observed that when I run `new MyClass({title: 'my title'}).save()` the value of the field `slug` is saved as `null`.

The line `Class.getBehavior('slug').generateSlug(doc)` never runs.
# Scenario

I have the following code added in a given `MyClass` definition:

``` js
// ...
  fields: {
      title: 'string'
  },
  behaviors: {
    slug: {
      fieldName: 'title',
      slugFieldName: 'slug',
      canUpdate: true,
      unique: true,
      separator: '-'
    }
  }
```

Notice that there is no definition of the field `slug` in my class, it is defined by the behavior.
# Debugging
1. The default value for the field is `null`. **Setting it as the `generateSlug` method could be a solution.**
   <img width="526" alt="screen shot 2015-11-10 at 14 00 54" src="https://cloud.githubusercontent.com/assets/181076/11062958/8955b8aa-87b3-11e5-98a9-b5a3d5314585.png">
2. When we run our `beforeSave` event listener, the value for the slug field is `null`. We then check for modifications in the field before we generate a new slug.
   <img width="472" alt="screen shot 2015-11-10 at 14 07 47" src="https://cloud.githubusercontent.com/assets/181076/11063094/7d610d6e-87b4-11e5-90bb-3d478aa78d98.png">
3. As there has not been any modifications to our data, **the function returns prematurely and no slug is generated**.

**Comment by zvictor** [comment]
It seems to be a duplicate of #3.

Still, can't we solve this by defining `generateSlug` as the default method?

**Comment by lukejagodzinski** [comment]
``` js
var doc = MyClass();
doc.set({title: 'my title'});
doc.save();
```

Will solve your problem

**Comment by zvictor** [comment]
I could see it in #3, as I said. Still, wouldn't it be a good idea to define generateSlug as the default method, if technically viable?

I understood the difference on the 2 mentioned ways to create an instance and the relevance of the `_id` field in these cases, but are you saying that it would be wrong to generate a slug when we import data?

**Comment by lukejagodzinski** [comment]
Hmm yes maybe generating a slug on importing data would be a good idea however it can collide with fetch data from collection. It would be possible to execute `generateSlug` method inside the `afterInit` event but after initiation the slug field is already filled and it may cause regeneration of the slug.

**Comment by lukejagodzinski** [comment]
I can't merge your PR because I'm not 100% sure that it won't break somebody's code. What I would propose you to do is the following implementation of your class:

``` js
MyClass = Astro.Class({
  /* ... */
  events: {
    afterInit: function() {
      MyClass.getBehavior('slug').generateSlug(doc);
    }
  },
  behaviors: {
    slug: { /* ... */ }
  }
});
```

Thanks to that you will achieve what your PR does but only for your class.

**Comment by zvictor** [comment]
Thank you for the tip and I understand your reasons to not merge it yet.

For now I will be using a package from my own fork. It can be added from
https://atmospherejs.com/zvictor/astronomy-slug-behavior in case anyone else is interested :)

**Comment by lukejagodzinski** [comment]
Ok good. Maybe I will add an option, which would tell on what "action" the slug should be generated.

``` js
slug: {
  generateOnInit: true,
  generateOnChange: true
}
```

**Comment by zvictor** [comment]
that's a very good idea! = )

**Comment by lukejagodzinski** [comment]
If you would like to implement that feature and create PR, it would be nice :) if you wish of course :).
If not I will implement it in the near future.

**Comment by NaderIkladious** [comment]
Facing the same issue, would be interesting if it can generate slug on init. :)

**Comment by lukejagodzinski** [comment]
I've implemented the `generateOnInit` option. I will publish it today. Closing this issue for now.
