### ISSUE TITLE
Fail when fieldName is nested object

### ISSUE THREAD

**Issue by MeKarina** [jagi/meteor-astronomy-slug-behavior#7]
```
behaviors: {
    slug: {
      fieldName: 'profile.name',
      slugFieldName: 'sP',
      canUpdate: false,
      unique: true,
      separator: '-'
    }
  }
```

Haven't support nested object for fieldName or my mistake?

thank you

**Comment by lukejagodzinski** [comment]
Behaviors for nested fields are not supported yet. I will be working on it but this feature will probably appear in the Astronomy 2.0

**Comment by MeKarina** [comment]
Don't push if it unnecessary. I can copy to parent as I don't like nested object

thank you
