### ISSUE TITLE
Remove slug after creation

### ISSUE THREAD

**Issue by NaderIkladious** [jagi/meteor-astronomy-slug-behavior#8]
Hello,

Is it possible to remove slug after using `Class.getBehavior("slug").generateSlug(this);` to add it?

I wrote a function:

``` javascript
removeSlug() {
   this.slug = null;
},
removeSlug2() {
   this.set('slug', null);
}

```

both of these functions are not working

I call them in a method call as

```
post.removeSlug();
post.save()
```

Thanks in advance,
Nader Ikladious.

**Comment by lukejagodzinski** [comment]
You have to set the `canUpdate` option to true

``` js
behaviors: {
  slug: {
    canUpdate: true
  }
}
```
